# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dacs/v1/dacs.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("dacs/v1/dacs.proto", :syntax => :proto3) do
    add_message "dacs.v1.DacsCmdP" do
      optional :preset_number, :int32, 1
      optional :capacity, :int32, 2
      optional :weight_unit, :int32, 3
      optional :weight_mode, :int32, 4
      optional :reference_weight, :double, 5
      optional :upper_delta_amount, :double, 6
      optional :lower_delta_amount, :double, 7
      optional :upper_delta_mode, :string, 8
      optional :lower_delta_mode, :string, 9
      optional :product_length_mm, :int32, 10
      optional :reject_start_delay_right, :int32, 11
      optional :reject_on_time_right, :int32, 12
      optional :reject_start_delay_left, :int32, 13
      optional :reject_on_time_left, :int32, 14
      optional :product_name, :string, 15
      optional :product_code, :string, 16
      optional :over_weight_accept, :int32, 17
      optional :metal_detection, :int32, 18
      optional :tare_weight, :double, 19
      optional :nominal_weight, :double, 20
      optional :t1_weight, :double, 21
      optional :t2_weight, :double, 22
      optional :ext1_out_delay_time, :int32, 23
      optional :ext2_out_delay_time, :int32, 24
      optional :ext3_out_delay_time, :int32, 25
      optional :ext4_out_delay_time, :int32, 26
      optional :ext5_out_delay_time, :int32, 27
      optional :ext6_out_delay_time, :int32, 28
      optional :ext1_input_delay_time, :int32, 29
      optional :ext2_input_delay_time, :int32, 30
      optional :continuous_no_good_count, :int32, 31
      optional :infeed_conveyor_speed, :int32, 32
      optional :weigh_conveyor_speed, :int32, 33
      optional :reject_conveyor_speed, :int32, 34
    end
  end
end

module Dacs
  module V1
    DacsCmdP = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dacs.v1.DacsCmdP").msgclass
  end
end
