// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.12.0
// source: omon/v1/omon.proto

package omon_v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OmonConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Ultrafly Integration
	MqttUri      string `protobuf:"bytes,5,opt,name=mqtt_uri,json=mqttUri,proto3" json:"mqtt_uri,omitempty"` // Example: "tcp://mosquitto:1883"
	MqttUsername string `protobuf:"bytes,6,opt,name=mqtt_username,json=mqttUsername,proto3" json:"mqtt_username,omitempty"`
	MqttPassword string `protobuf:"bytes,7,opt,name=mqtt_password,json=mqttPassword,proto3" json:"mqtt_password,omitempty"`
	MqttClientId string `protobuf:"bytes,8,opt,name=mqtt_client_id,json=mqttClientId,proto3" json:"mqtt_client_id,omitempty"`
	UksrState    string `protobuf:"bytes,9,opt,name=uksr_state,json=uksrState,proto3" json:"uksr_state,omitempty"`
	MineralPath  string `protobuf:"bytes,10,opt,name=mineral_path,json=mineralPath,proto3" json:"mineral_path,omitempty"` // License path
}

func (x *OmonConfig) Reset() {
	*x = OmonConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omon_v1_omon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OmonConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmonConfig) ProtoMessage() {}

func (x *OmonConfig) ProtoReflect() protoreflect.Message {
	mi := &file_omon_v1_omon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmonConfig.ProtoReflect.Descriptor instead.
func (*OmonConfig) Descriptor() ([]byte, []int) {
	return file_omon_v1_omon_proto_rawDescGZIP(), []int{0}
}

func (x *OmonConfig) GetMqttUri() string {
	if x != nil {
		return x.MqttUri
	}
	return ""
}

func (x *OmonConfig) GetMqttUsername() string {
	if x != nil {
		return x.MqttUsername
	}
	return ""
}

func (x *OmonConfig) GetMqttPassword() string {
	if x != nil {
		return x.MqttPassword
	}
	return ""
}

func (x *OmonConfig) GetMqttClientId() string {
	if x != nil {
		return x.MqttClientId
	}
	return ""
}

func (x *OmonConfig) GetUksrState() string {
	if x != nil {
		return x.UksrState
	}
	return ""
}

func (x *OmonConfig) GetMineralPath() string {
	if x != nil {
		return x.MineralPath
	}
	return ""
}

type OmonStateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     int32  `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	AntennaNo int32  `protobuf:"varint,2,opt,name=antenna_no,json=antennaNo,proto3" json:"antenna_no,omitempty"`
	State     string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // Restart, AwaitBox, ReadTag, SendWeight, AwaitWeight, LogResult, Error
}

func (x *OmonStateMessage) Reset() {
	*x = OmonStateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omon_v1_omon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OmonStateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmonStateMessage) ProtoMessage() {}

func (x *OmonStateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_omon_v1_omon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmonStateMessage.ProtoReflect.Descriptor instead.
func (*OmonStateMessage) Descriptor() ([]byte, []int) {
	return file_omon_v1_omon_proto_rawDescGZIP(), []int{1}
}

func (x *OmonStateMessage) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *OmonStateMessage) GetAntennaNo() int32 {
	if x != nil {
		return x.AntennaNo
	}
	return 0
}

func (x *OmonStateMessage) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type OmonStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`     // Inform UI about Error Problem
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Just annoucing state
}

func (x *OmonStatus) Reset() {
	*x = OmonStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omon_v1_omon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OmonStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmonStatus) ProtoMessage() {}

func (x *OmonStatus) ProtoReflect() protoreflect.Message {
	mi := &file_omon_v1_omon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmonStatus.ProtoReflect.Descriptor instead.
func (*OmonStatus) Descriptor() ([]byte, []int) {
	return file_omon_v1_omon_proto_rawDescGZIP(), []int{2}
}

func (x *OmonStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OmonStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_omon_v1_omon_proto protoreflect.FileDescriptor

var file_omon_v1_omon_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0xd9, 0x01,
	0x0a, 0x0a, 0x4f, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x71, 0x74, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x71, 0x74, 0x74, 0x55, 0x72, 0x69, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x71, 0x74, 0x74, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6d, 0x71, 0x74, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x6d, 0x71, 0x74, 0x74, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x71, 0x74, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x71, 0x74, 0x74, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x71, 0x74, 0x74, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6b, 0x73, 0x72, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x6b, 0x73,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x69,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x22, 0x5d, 0x0a, 0x10, 0x4f, 0x6d, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x6e, 0x74, 0x65, 0x6e, 0x6e, 0x61, 0x5f, 0x6e,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x6e, 0x74, 0x65, 0x6e, 0x6e, 0x61,
	0x4e, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x3c, 0x0a, 0x0a, 0x4f, 0x6d, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x6f, 0x6d, 0x6f, 0x6e, 0x2f, 0x76,
	0x31, 0x3b, 0x6f, 0x6d, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_omon_v1_omon_proto_rawDescOnce sync.Once
	file_omon_v1_omon_proto_rawDescData = file_omon_v1_omon_proto_rawDesc
)

func file_omon_v1_omon_proto_rawDescGZIP() []byte {
	file_omon_v1_omon_proto_rawDescOnce.Do(func() {
		file_omon_v1_omon_proto_rawDescData = protoimpl.X.CompressGZIP(file_omon_v1_omon_proto_rawDescData)
	})
	return file_omon_v1_omon_proto_rawDescData
}

var file_omon_v1_omon_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_omon_v1_omon_proto_goTypes = []interface{}{
	(*OmonConfig)(nil),       // 0: omon.v1.OmonConfig
	(*OmonStateMessage)(nil), // 1: omon.v1.OmonStateMessage
	(*OmonStatus)(nil),       // 2: omon.v1.OmonStatus
}
var file_omon_v1_omon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_omon_v1_omon_proto_init() }
func file_omon_v1_omon_proto_init() {
	if File_omon_v1_omon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_omon_v1_omon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OmonConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omon_v1_omon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OmonStateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omon_v1_omon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OmonStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_omon_v1_omon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_omon_v1_omon_proto_goTypes,
		DependencyIndexes: file_omon_v1_omon_proto_depIdxs,
		MessageInfos:      file_omon_v1_omon_proto_msgTypes,
	}.Build()
	File_omon_v1_omon_proto = out.File
	file_omon_v1_omon_proto_rawDesc = nil
	file_omon_v1_omon_proto_goTypes = nil
	file_omon_v1_omon_proto_depIdxs = nil
}
