# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dfruit/v1/dfruit.proto

require 'google/protobuf'

require 'ffruit/v1/ffruit_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("dfruit/v1/dfruit.proto", :syntax => :proto3) do
    add_message "dfruit.v1.DfruitConfig" do
      optional :mqtt_uri, :string, 5
      optional :mqtt_username, :string, 6
      optional :mqtt_password, :string, 7
      optional :mqtt_client_id, :string, 8
      optional :uksr_state, :string, 9
      optional :mineral_path, :string, 10
      optional :watch_zone, :string, 11
      optional :attach_rssi, :int32, 12
      optional :detach_rssi, :int32, 13
      optional :inventory_settling_rounds, :int32, 15
      optional :gorm_db_engine, :string, 80
      optional :gorm_db_url, :string, 81
      optional :dummy_wait_ms, :int32, 90
    end
    add_message "dfruit.v1.DfruitStateMessage" do
      optional :error, :int32, 1
      optional :antenna_no, :int32, 2
      optional :state, :string, 3
    end
    add_message "dfruit.v1.DfruitStatus" do
      optional :error, :string, 1
      optional :message, :string, 2
    end
    add_message "dfruit.v1.DfruitSignEpc" do
      optional :epc, :string, 1
      optional :app_id, :bytes, 2
      optional :key, :bytes, 3
      optional :tid, :bytes, 4
      optional :serial_bytes, :bytes, 5
      optional :company_bytes, :bytes, 6
      optional :product_bytes, :bytes, 7
      optional :force, :bool, 20
    end
    add_message "dfruit.v1.DfruitPrepareReservedBlock" do
      optional :epc, :string, 1
      optional :force, :bool, 2
    end
    add_message "dfruit.v1.DfruitRegisterBox" do
      optional :epc, :string, 1
      optional :app_id, :bytes, 2
    end
    add_message "dfruit.v1.DfruitUserBankInit" do
      optional :epc, :string, 1
      optional :app_id, :bytes, 2
    end
    add_message "dfruit.v1.DfruitUserBankInitSpecialCommand" do
      optional :epc, :string, 1
      optional :app_id, :bytes, 2
      optional :command, :enum, 3, "ffruit.v1.FfruitSpecialCommand"
    end
    add_message "dfruit.v1.DfruitBarcode" do
      optional :scanned, :string, 1
      optional :confirmed, :string, 2
    end
    add_message "dfruit.v1.DfruitOperation" do
      optional :initial_epc_bank, :string, 1
      optional :initial_tid_bank, :string, 2
      optional :initial_user_bank, :string, 3
      optional :barcode_as_scanned, :string, 4
      optional :barcode_as_confirmed, :string, 5
      optional :final_epc, :string, 10
      optional :final_epc_found, :bool, 11
      optional :tag_locked, :bool, 20
    end
  end
end

module Dfruit
  module V1
    DfruitConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dfruit.v1.DfruitConfig").msgclass
    DfruitStateMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dfruit.v1.DfruitStateMessage").msgclass
    DfruitStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dfruit.v1.DfruitStatus").msgclass
    DfruitSignEpc = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dfruit.v1.DfruitSignEpc").msgclass
    DfruitPrepareReservedBlock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dfruit.v1.DfruitPrepareReservedBlock").msgclass
    DfruitRegisterBox = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dfruit.v1.DfruitRegisterBox").msgclass
    DfruitUserBankInit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dfruit.v1.DfruitUserBankInit").msgclass
    DfruitUserBankInitSpecialCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dfruit.v1.DfruitUserBankInitSpecialCommand").msgclass
    DfruitBarcode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dfruit.v1.DfruitBarcode").msgclass
    DfruitOperation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dfruit.v1.DfruitOperation").msgclass
  end
end
