// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.12.0
// source: ukey/v1/ukey.proto

package ukey_v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// message UkeySetRequest {  // For the sake of sanity, we send a UkeySetRequest with a Ukey body so that it can be used immediately upon Unmarshal with other utilities
type Ukey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    uint32 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	GenerationId []byte `protobuf:"bytes,2,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"` // Typical 2 Byte Generation ID (Currently "ZZ")
	AppId        []byte `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                      // Typical 2 Byte App ID (Currently "TF")
	EpcBase      []byte `protobuf:"bytes,4,opt,name=epc_base,json=epcBase,proto3" json:"epc_base,omitempty"`                // EPC Signing Key Base - Required for all ultrafly stations
	EpcStyle     string `protobuf:"bytes,5,opt,name=epc_style,json=epcStyle,proto3" json:"epc_style,omitempty"`             // Can use this to determine the algorithm for diversification
	AccessBase   []byte `protobuf:"bytes,6,opt,name=access_base,json=accessBase,proto3" json:"access_base,omitempty"`       // Access Key Base - Required for all ultrafly stations
	AccessStyle  string `protobuf:"bytes,7,opt,name=access_style,json=accessStyle,proto3" json:"access_style,omitempty"`    // Can use this to determine the algorithm for diversification
	KillBase     []byte `protobuf:"bytes,8,opt,name=kill_base,json=killBase,proto3" json:"kill_base,omitempty"`             // Kill Key Base // Only Personalization@TapIt should have this
	KillStyle    string `protobuf:"bytes,9,opt,name=kill_style,json=killStyle,proto3" json:"kill_style,omitempty"`          // Can use this to determine the algorithm for diversification
	Confirmation []byte `protobuf:"bytes,11,opt,name=confirmation,proto3" json:"confirmation,omitempty"`                    // Confirmation Code to confirm this packet is real
}

func (x *Ukey) Reset() {
	*x = Ukey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ukey_v1_ukey_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ukey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ukey) ProtoMessage() {}

func (x *Ukey) ProtoReflect() protoreflect.Message {
	mi := &file_ukey_v1_ukey_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ukey.ProtoReflect.Descriptor instead.
func (*Ukey) Descriptor() ([]byte, []int) {
	return file_ukey_v1_ukey_proto_rawDescGZIP(), []int{0}
}

func (x *Ukey) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Ukey) GetGenerationId() []byte {
	if x != nil {
		return x.GenerationId
	}
	return nil
}

func (x *Ukey) GetAppId() []byte {
	if x != nil {
		return x.AppId
	}
	return nil
}

func (x *Ukey) GetEpcBase() []byte {
	if x != nil {
		return x.EpcBase
	}
	return nil
}

func (x *Ukey) GetEpcStyle() string {
	if x != nil {
		return x.EpcStyle
	}
	return ""
}

func (x *Ukey) GetAccessBase() []byte {
	if x != nil {
		return x.AccessBase
	}
	return nil
}

func (x *Ukey) GetAccessStyle() string {
	if x != nil {
		return x.AccessStyle
	}
	return ""
}

func (x *Ukey) GetKillBase() []byte {
	if x != nil {
		return x.KillBase
	}
	return nil
}

func (x *Ukey) GetKillStyle() string {
	if x != nil {
		return x.KillStyle
	}
	return ""
}

func (x *Ukey) GetConfirmation() []byte {
	if x != nil {
		return x.Confirmation
	}
	return nil
}

type UkeySetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId uint32 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success   bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UkeySetResponse) Reset() {
	*x = UkeySetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ukey_v1_ukey_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UkeySetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UkeySetResponse) ProtoMessage() {}

func (x *UkeySetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ukey_v1_ukey_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UkeySetResponse.ProtoReflect.Descriptor instead.
func (*UkeySetResponse) Descriptor() ([]byte, []int) {
	return file_ukey_v1_ukey_proto_rawDescGZIP(), []int{1}
}

func (x *UkeySetResponse) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *UkeySetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UkeySetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ukey_v1_ukey_proto protoreflect.FileDescriptor

var file_ukey_v1_ukey_proto_rawDesc = []byte{
	0x0a, 0x12, 0x75, 0x6b, 0x65, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x6b, 0x65, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x6b, 0x65, 0x79, 0x2e, 0x76, 0x31, 0x22, 0xbd, 0x02,
	0x0a, 0x04, 0x55, 0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x70, 0x63, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x65, 0x70, 0x63, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x65, 0x70, 0x63, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x70, 0x63, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x61, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x6b, 0x69, 0x6c, 0x6c, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x69,
	0x6c, 0x6c, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6b, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x64, 0x0a,
	0x0f, 0x55, 0x6b, 0x65, 0x79, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x78, 0x32, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x75, 0x6c, 0x74, 0x72, 0x61,
	0x66, 0x6c, 0x79, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x6b, 0x65, 0x79, 0x2f, 0x76, 0x31, 0x3b,
	0x75, 0x6b, 0x65, 0x79, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ukey_v1_ukey_proto_rawDescOnce sync.Once
	file_ukey_v1_ukey_proto_rawDescData = file_ukey_v1_ukey_proto_rawDesc
)

func file_ukey_v1_ukey_proto_rawDescGZIP() []byte {
	file_ukey_v1_ukey_proto_rawDescOnce.Do(func() {
		file_ukey_v1_ukey_proto_rawDescData = protoimpl.X.CompressGZIP(file_ukey_v1_ukey_proto_rawDescData)
	})
	return file_ukey_v1_ukey_proto_rawDescData
}

var file_ukey_v1_ukey_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ukey_v1_ukey_proto_goTypes = []interface{}{
	(*Ukey)(nil),            // 0: ukey.v1.Ukey
	(*UkeySetResponse)(nil), // 1: ukey.v1.UkeySetResponse
}
var file_ukey_v1_ukey_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ukey_v1_ukey_proto_init() }
func file_ukey_v1_ukey_proto_init() {
	if File_ukey_v1_ukey_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ukey_v1_ukey_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ukey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ukey_v1_ukey_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UkeySetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ukey_v1_ukey_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ukey_v1_ukey_proto_goTypes,
		DependencyIndexes: file_ukey_v1_ukey_proto_depIdxs,
		MessageInfos:      file_ukey_v1_ukey_proto_msgTypes,
	}.Build()
	File_ukey_v1_ukey_proto = out.File
	file_ukey_v1_ukey_proto_rawDesc = nil
	file_ukey_v1_ukey_proto_goTypes = nil
	file_ukey_v1_ukey_proto_depIdxs = nil
}
