# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clearly/v1/clearly.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("clearly/v1/clearly.proto", :syntax => :proto3) do
    add_message "clearly.v1.Debug" do
      optional :key, :string, 1
      optional :i1, :int32, 10
      optional :i2, :int32, 11
      optional :i3, :int32, 12
      optional :i4, :int32, 13
    end
    add_message "clearly.v1.Dfev2" do
      optional :command, :enum, 1, "clearly.v1.Dfev2.Command"
      repeated :commands, :message, 2, "clearly.v1.Dfev2"
      optional :ping_id, :int32, 3
      optional :pong_id, :int32, 4
      optional :success, :bool, 5
      optional :error_code, :int32, 6
      optional :fail_position, :int32, 7
      optional :hint_deauthed, :bool, 8
      optional :uid, :bytes, 9
      optional :i1, :int32, 11
      optional :i2, :int32, 12
      optional :i3, :int32, 13
      optional :i4, :int32, 14
      optional :i5, :int32, 15
      optional :i6, :int32, 16
      optional :i7, :int32, 17
      optional :i8, :int32, 18
      optional :i9, :int32, 19
      optional :b1, :bytes, 21
      optional :b2, :bytes, 22
      optional :b3, :bytes, 23
      optional :b4, :bytes, 24
      optional :s1, :string, 31
      optional :s2, :string, 32
      optional :s3, :string, 33
      optional :s4, :string, 34
    end
    add_enum "clearly.v1.Dfev2.Command" do
      value :DEBUG, 0
      value :EZ_BATCH_COMMAND, 58288
      value :EZ_MASTER_SETUP, 58034
      value :EZ_AUTH_APP, 58036
      value :EZ_APP_ENSURE, 58037
      value :AUTH_2TDEA, 57889
      value :AUTH_ISO, 57890
      value :AUTH_AES, 57891
      value :AUTH_EV2_FIRST, 57892
      value :AUTH_MASTER_DEFAULT, 58033
      value :AUTH_MASTER_DIVERSIFIED_EV2, 58035
      value :GET_FREEMEM, 57905
      value :FORMAT_CARD, 57906
      value :SET_CONFIURATION, 57907
      value :GET_VERSION, 57908
      value :GET_UID, 57909
      value :CHANGE_KEY, 57921
      value :CHANGE_KEY_EV2, 57922
      value :INITIALIZE_KEY_SET, 57923
      value :FINALIZE_KEY_SET, 57924
      value :ROLL_KEY_SET, 57925
      value :GET_KEY_SETTINGS, 57926
      value :CHANGE_KEY_SETTINGS, 57927
      value :GET_KEY_VERSION, 57928
      value :APP_CREATE, 57937
      value :APP_DELETE, 57938
      value :APP_CREATE_DELEGATED, 57939
      value :APP_SELECT, 57940
      value :APP_GET_IDS, 57941
      value :APP_GET_DFNAMES, 57942
      value :APP_GET_DELETEGATED_INFO, 57943
      value :FILE_CREATE_STD, 57953
      value :FILE_CREATE_BACKUP, 57954
      value :FILE_CREATE_VALUE, 57955
      value :FILE_CREATE_LINEAR, 57956
      value :FILE_CREATE_CYCLIC, 57957
      value :FILE_CREATE_TXNMAC, 57958
      value :FILE_DELETE, 57959
      value :FILE_GET_IDS, 57960
      value :FILE_GET_ISOIDS, 57961
      value :FILE_GET_SETTINGS, 57962
      value :FILE_CHANGE_SETTINGS, 57963
      value :DATA_READ, 57969
      value :DATA_WRITE, 57970
      value :DATA_GET_VALUE, 57971
      value :DATA_CREDIT, 57972
      value :DATA_LIMITED_CREDIT, 57973
      value :DATA_DEBIT, 57974
      value :DATA_READ_RECORDS, 57975
      value :DATA_WRITE_RECORD, 57976
      value :DATA_UPDATE_RECORD, 57977
      value :DATA_CLEAR_RECORD_FILE, 57978
      value :EZ_READ_RECORDS, 58231
      value :EZ_READ_RECORDS_REVERSE, 58232
      value :SAFETY_TIMED_DATA_WRITE_RECORD, 58488
      value :TXN_COMMIT, 57985
      value :TXN_ABORT, 57986
      value :TXN_COMMIT_READER_ID, 57987
      value :EZ_CONFIRM_PROX_CHECK, 58291
      value :READ_SIG, 58049
    end
    add_message "clearly.v1.SafetyRecord" do
      optional :timestamp, :uint32, 1
      optional :data, :bytes, 2
    end
    add_message "clearly.v1.Ident" do
      optional :chipid, :string, 1
      optional :app_project_name, :string, 2
      optional :app_version, :string, 3
      optional :app_date, :string, 4
      optional :app_time, :string, 5
      optional :app_idf_ver, :string, 6
    end
    add_message "clearly.v1.Gas" do
      optional :voltage, :float, 1
      optional :current, :float, 2
      optional :state_of_charge, :float, 3
      optional :cycles, :uint32, 4
      optional :age, :uint32, 5
      optional :time_to_full, :uint32, 6
      optional :time_to_empty, :uint32, 7
      optional :bq8, :uint32, 18
      optional :bq9, :bytes, 19
    end
    add_message "clearly.v1.Wifista" do
      optional :bssid, :string, 1
      optional :ssid, :string, 2
      optional :channel_primary, :uint32, 3
      optional :rssi, :int32, 4
      optional :is_11b, :bool, 10
      optional :is_11g, :bool, 11
      optional :is_11n, :bool, 12
      optional :country, :string, 20
      optional :channel_start, :uint32, 21
      optional :channel_count, :uint32, 22
    end
    add_message "clearly.v1.Activated" do
      optional :type, :string, 1
      optional :uid, :bytes, 2
      optional :sak, :uint32, 3
      optional :atqa, :bytes, 4
    end
    add_message "clearly.v1.Deactivated" do
      optional :uid, :bytes, 2
    end
    add_message "clearly.v1.LcdDisplay" do
      optional :line1, :string, 1
      optional :line2, :string, 2
      optional :duration_ms, :uint32, 3
      optional :backlight, :bool, 4
    end
    add_message "clearly.v1.Checkpoint" do
      optional :id, :uint32, 1
      optional :name, :string, 2
      optional :starts_at, :uint32, 3
      optional :ends_at, :uint32, 4
      optional :required_options, :string, 5
      optional :strike_options, :string, 6
      optional :allowed_options, :string, 7
      optional :code, :string, 8
      optional :scan_limit, :uint32, 9
      optional :min_level_1, :uint32, 10
      optional :max_level_1, :uint32, 11
      optional :led_ok_ms, :uint32, 12
      optional :led_fail_ms, :uint32, 13
      optional :price, :uint32, 14
      optional :stars_allowed, :bool, 15
      optional :stars_price, :uint32, 16
    end
    add_message "clearly.v1.CheckpointArray" do
      repeated :checkpoints, :message, 1, "clearly.v1.Checkpoint"
    end
    add_message "clearly.v1.KeySpec" do
      optional :protocol, :string, 1
      optional :number, :uint32, 2
      optional :position, :uint32, 3
      optional :version, :uint32, 4
      optional :rawbytes, :bytes, 5
      optional :usage, :string, 6
      optional :diversify_by_swcmac, :bool, 10
      optional :diversify_by_keystore, :bool, 11
      optional :diversify_by_samav1, :bool, 12
      optional :diversify_by_samav2, :bool, 13
      optional :diversify_by_samav3, :bool, 14
    end
    add_message "clearly.v1.KeyRing" do
      repeated :keys, :message, 1, "clearly.v1.KeySpec"
    end
  end
end

module Clearly
  module V1
    Debug = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.Debug").msgclass
    Dfev2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.Dfev2").msgclass
    Dfev2::Command = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.Dfev2.Command").enummodule
    SafetyRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.SafetyRecord").msgclass
    Ident = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.Ident").msgclass
    Gas = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.Gas").msgclass
    Wifista = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.Wifista").msgclass
    Activated = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.Activated").msgclass
    Deactivated = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.Deactivated").msgclass
    LcdDisplay = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.LcdDisplay").msgclass
    Checkpoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.Checkpoint").msgclass
    CheckpointArray = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.CheckpointArray").msgclass
    KeySpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.KeySpec").msgclass
    KeyRing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("clearly.v1.KeyRing").msgclass
  end
end
