# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneshelf/v1/oneshelf.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("oneshelf/v1/oneshelf.proto", :syntax => :proto3) do
    add_message "oneshelf.v1.GpioMapping" do
      optional :pin_number, :uint32, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :direction, :string, 4
      optional :init_high, :bool, 5
      optional :debounce_ms, :uint32, 6
    end
    add_message "oneshelf.v1.OneshelfConfig" do
      optional :serial_port_name, :string, 1
      optional :mqtt_uri, :string, 5
      optional :mqtt_username, :string, 6
      optional :mqtt_password, :string, 7
      optional :mqtt_client_id, :string, 8
      optional :mineral_path, :string, 10
      optional :reader_name, :string, 11
      optional :mac_address, :string, 12
      optional :uhf_country, :string, 13
      optional :antennas_on_str, :string, 20
      optional :inventory_sec, :int32, 21
      optional :rssi_pre_filter_minimum, :int32, 22
      optional :wait_ms, :int32, 31
      optional :fading_ms, :int32, 32
      optional :lost_ms, :int32, 33
      optional :url_v1, :string, 70
      optional :inventory_url, :string, 71
      optional :events_url, :string, 72
      optional :pcb_major_version, :int32, 80
      optional :pcb_minor_version, :int32, 81
      optional :spotlight, :string, 90
      optional :verbosity, :string, 91
      optional :test_gpo, :bool, 92
      repeated :gpio_mappings, :message, 100, "oneshelf.v1.GpioMapping"
    end
  end
end

module Oneshelf
  module V1
    GpioMapping = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("oneshelf.v1.GpioMapping").msgclass
    OneshelfConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("oneshelf.v1.OneshelfConfig").msgclass
  end
end
