// source: oneshelf/v1/oneshelf.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.oneshelf.v1.GpioMapping', null, global);
goog.exportSymbol('proto.oneshelf.v1.OneshelfConfig', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.oneshelf.v1.GpioMapping = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.oneshelf.v1.GpioMapping, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.oneshelf.v1.GpioMapping.displayName = 'proto.oneshelf.v1.GpioMapping';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.oneshelf.v1.OneshelfConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.oneshelf.v1.OneshelfConfig.repeatedFields_, null);
};
goog.inherits(proto.oneshelf.v1.OneshelfConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.oneshelf.v1.OneshelfConfig.displayName = 'proto.oneshelf.v1.OneshelfConfig';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.oneshelf.v1.GpioMapping.prototype.toObject = function(opt_includeInstance) {
  return proto.oneshelf.v1.GpioMapping.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.oneshelf.v1.GpioMapping} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oneshelf.v1.GpioMapping.toObject = function(includeInstance, msg) {
  var f, obj = {
    pinNumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    direction: jspb.Message.getFieldWithDefault(msg, 4, ""),
    initHigh: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    debounceMs: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.oneshelf.v1.GpioMapping}
 */
proto.oneshelf.v1.GpioMapping.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.oneshelf.v1.GpioMapping;
  return proto.oneshelf.v1.GpioMapping.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.oneshelf.v1.GpioMapping} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.oneshelf.v1.GpioMapping}
 */
proto.oneshelf.v1.GpioMapping.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPinNumber(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDirection(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInitHigh(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDebounceMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.oneshelf.v1.GpioMapping.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.oneshelf.v1.GpioMapping.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.oneshelf.v1.GpioMapping} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oneshelf.v1.GpioMapping.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPinNumber();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDirection();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getInitHigh();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getDebounceMs();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
};


/**
 * optional uint32 pin_number = 1;
 * @return {number}
 */
proto.oneshelf.v1.GpioMapping.prototype.getPinNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.oneshelf.v1.GpioMapping} returns this
 */
proto.oneshelf.v1.GpioMapping.prototype.setPinNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.oneshelf.v1.GpioMapping.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.GpioMapping} returns this
 */
proto.oneshelf.v1.GpioMapping.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.oneshelf.v1.GpioMapping.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.GpioMapping} returns this
 */
proto.oneshelf.v1.GpioMapping.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string direction = 4;
 * @return {string}
 */
proto.oneshelf.v1.GpioMapping.prototype.getDirection = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.GpioMapping} returns this
 */
proto.oneshelf.v1.GpioMapping.prototype.setDirection = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool init_high = 5;
 * @return {boolean}
 */
proto.oneshelf.v1.GpioMapping.prototype.getInitHigh = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.oneshelf.v1.GpioMapping} returns this
 */
proto.oneshelf.v1.GpioMapping.prototype.setInitHigh = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional uint32 debounce_ms = 6;
 * @return {number}
 */
proto.oneshelf.v1.GpioMapping.prototype.getDebounceMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.oneshelf.v1.GpioMapping} returns this
 */
proto.oneshelf.v1.GpioMapping.prototype.setDebounceMs = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.oneshelf.v1.OneshelfConfig.repeatedFields_ = [100];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.oneshelf.v1.OneshelfConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.oneshelf.v1.OneshelfConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oneshelf.v1.OneshelfConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    serialPortName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mqttUri: jspb.Message.getFieldWithDefault(msg, 5, ""),
    mqttUsername: jspb.Message.getFieldWithDefault(msg, 6, ""),
    mqttPassword: jspb.Message.getFieldWithDefault(msg, 7, ""),
    mqttClientId: jspb.Message.getFieldWithDefault(msg, 8, ""),
    mineralPath: jspb.Message.getFieldWithDefault(msg, 10, ""),
    readerName: jspb.Message.getFieldWithDefault(msg, 11, ""),
    macAddress: jspb.Message.getFieldWithDefault(msg, 12, ""),
    uhfCountry: jspb.Message.getFieldWithDefault(msg, 13, ""),
    antennasOnStr: jspb.Message.getFieldWithDefault(msg, 20, ""),
    inventorySec: jspb.Message.getFieldWithDefault(msg, 21, 0),
    rssiPreFilterMinimum: jspb.Message.getFieldWithDefault(msg, 22, 0),
    waitMs: jspb.Message.getFieldWithDefault(msg, 31, 0),
    fadingMs: jspb.Message.getFieldWithDefault(msg, 32, 0),
    lostMs: jspb.Message.getFieldWithDefault(msg, 33, 0),
    urlV1: jspb.Message.getFieldWithDefault(msg, 70, ""),
    inventoryUrl: jspb.Message.getFieldWithDefault(msg, 71, ""),
    eventsUrl: jspb.Message.getFieldWithDefault(msg, 72, ""),
    pcbMajorVersion: jspb.Message.getFieldWithDefault(msg, 80, 0),
    pcbMinorVersion: jspb.Message.getFieldWithDefault(msg, 81, 0),
    spotlight: jspb.Message.getFieldWithDefault(msg, 90, ""),
    verbosity: jspb.Message.getFieldWithDefault(msg, 91, ""),
    testGpo: jspb.Message.getBooleanFieldWithDefault(msg, 92, false),
    gpioMappingsList: jspb.Message.toObjectList(msg.getGpioMappingsList(),
    proto.oneshelf.v1.GpioMapping.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.oneshelf.v1.OneshelfConfig}
 */
proto.oneshelf.v1.OneshelfConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.oneshelf.v1.OneshelfConfig;
  return proto.oneshelf.v1.OneshelfConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.oneshelf.v1.OneshelfConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.oneshelf.v1.OneshelfConfig}
 */
proto.oneshelf.v1.OneshelfConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSerialPortName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMqttUri(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMqttUsername(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setMqttPassword(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setMqttClientId(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setMineralPath(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setReaderName(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setMacAddress(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setUhfCountry(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setAntennasOnStr(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInventorySec(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRssiPreFilterMinimum(value);
      break;
    case 31:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWaitMs(value);
      break;
    case 32:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFadingMs(value);
      break;
    case 33:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLostMs(value);
      break;
    case 70:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrlV1(value);
      break;
    case 71:
      var value = /** @type {string} */ (reader.readString());
      msg.setInventoryUrl(value);
      break;
    case 72:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventsUrl(value);
      break;
    case 80:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPcbMajorVersion(value);
      break;
    case 81:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPcbMinorVersion(value);
      break;
    case 90:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpotlight(value);
      break;
    case 91:
      var value = /** @type {string} */ (reader.readString());
      msg.setVerbosity(value);
      break;
    case 92:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTestGpo(value);
      break;
    case 100:
      var value = new proto.oneshelf.v1.GpioMapping;
      reader.readMessage(value,proto.oneshelf.v1.GpioMapping.deserializeBinaryFromReader);
      msg.addGpioMappings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.oneshelf.v1.OneshelfConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.oneshelf.v1.OneshelfConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oneshelf.v1.OneshelfConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSerialPortName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMqttUri();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMqttUsername();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getMqttPassword();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getMqttClientId();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getMineralPath();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getReaderName();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getMacAddress();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getUhfCountry();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getAntennasOnStr();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getInventorySec();
  if (f !== 0) {
    writer.writeInt32(
      21,
      f
    );
  }
  f = message.getRssiPreFilterMinimum();
  if (f !== 0) {
    writer.writeInt32(
      22,
      f
    );
  }
  f = message.getWaitMs();
  if (f !== 0) {
    writer.writeInt32(
      31,
      f
    );
  }
  f = message.getFadingMs();
  if (f !== 0) {
    writer.writeInt32(
      32,
      f
    );
  }
  f = message.getLostMs();
  if (f !== 0) {
    writer.writeInt32(
      33,
      f
    );
  }
  f = message.getUrlV1();
  if (f.length > 0) {
    writer.writeString(
      70,
      f
    );
  }
  f = message.getInventoryUrl();
  if (f.length > 0) {
    writer.writeString(
      71,
      f
    );
  }
  f = message.getEventsUrl();
  if (f.length > 0) {
    writer.writeString(
      72,
      f
    );
  }
  f = message.getPcbMajorVersion();
  if (f !== 0) {
    writer.writeInt32(
      80,
      f
    );
  }
  f = message.getPcbMinorVersion();
  if (f !== 0) {
    writer.writeInt32(
      81,
      f
    );
  }
  f = message.getSpotlight();
  if (f.length > 0) {
    writer.writeString(
      90,
      f
    );
  }
  f = message.getVerbosity();
  if (f.length > 0) {
    writer.writeString(
      91,
      f
    );
  }
  f = message.getTestGpo();
  if (f) {
    writer.writeBool(
      92,
      f
    );
  }
  f = message.getGpioMappingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      100,
      f,
      proto.oneshelf.v1.GpioMapping.serializeBinaryToWriter
    );
  }
};


/**
 * optional string serial_port_name = 1;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getSerialPortName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setSerialPortName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string mqtt_uri = 5;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getMqttUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setMqttUri = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string mqtt_username = 6;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getMqttUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setMqttUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string mqtt_password = 7;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getMqttPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setMqttPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string mqtt_client_id = 8;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getMqttClientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setMqttClientId = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string mineral_path = 10;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getMineralPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setMineralPath = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string reader_name = 11;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getReaderName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setReaderName = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string mac_address = 12;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getMacAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setMacAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string uhf_country = 13;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getUhfCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setUhfCountry = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string antennas_on_str = 20;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getAntennasOnStr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setAntennasOnStr = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional int32 inventory_sec = 21;
 * @return {number}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getInventorySec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/**
 * @param {number} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setInventorySec = function(value) {
  return jspb.Message.setProto3IntField(this, 21, value);
};


/**
 * optional int32 rssi_pre_filter_minimum = 22;
 * @return {number}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getRssiPreFilterMinimum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/**
 * @param {number} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setRssiPreFilterMinimum = function(value) {
  return jspb.Message.setProto3IntField(this, 22, value);
};


/**
 * optional int32 wait_ms = 31;
 * @return {number}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getWaitMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 31, 0));
};


/**
 * @param {number} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setWaitMs = function(value) {
  return jspb.Message.setProto3IntField(this, 31, value);
};


/**
 * optional int32 fading_ms = 32;
 * @return {number}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getFadingMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 32, 0));
};


/**
 * @param {number} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setFadingMs = function(value) {
  return jspb.Message.setProto3IntField(this, 32, value);
};


/**
 * optional int32 lost_ms = 33;
 * @return {number}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getLostMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 33, 0));
};


/**
 * @param {number} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setLostMs = function(value) {
  return jspb.Message.setProto3IntField(this, 33, value);
};


/**
 * optional string url_v1 = 70;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getUrlV1 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 70, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setUrlV1 = function(value) {
  return jspb.Message.setProto3StringField(this, 70, value);
};


/**
 * optional string inventory_url = 71;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getInventoryUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 71, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setInventoryUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 71, value);
};


/**
 * optional string events_url = 72;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getEventsUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 72, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setEventsUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 72, value);
};


/**
 * optional int32 pcb_major_version = 80;
 * @return {number}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getPcbMajorVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 80, 0));
};


/**
 * @param {number} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setPcbMajorVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 80, value);
};


/**
 * optional int32 pcb_minor_version = 81;
 * @return {number}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getPcbMinorVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 81, 0));
};


/**
 * @param {number} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setPcbMinorVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 81, value);
};


/**
 * optional string spotlight = 90;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getSpotlight = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 90, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setSpotlight = function(value) {
  return jspb.Message.setProto3StringField(this, 90, value);
};


/**
 * optional string verbosity = 91;
 * @return {string}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getVerbosity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 91, ""));
};


/**
 * @param {string} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setVerbosity = function(value) {
  return jspb.Message.setProto3StringField(this, 91, value);
};


/**
 * optional bool test_gpo = 92;
 * @return {boolean}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getTestGpo = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 92, false));
};


/**
 * @param {boolean} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.setTestGpo = function(value) {
  return jspb.Message.setProto3BooleanField(this, 92, value);
};


/**
 * repeated GpioMapping gpio_mappings = 100;
 * @return {!Array<!proto.oneshelf.v1.GpioMapping>}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.getGpioMappingsList = function() {
  return /** @type{!Array<!proto.oneshelf.v1.GpioMapping>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.oneshelf.v1.GpioMapping, 100));
};


/**
 * @param {!Array<!proto.oneshelf.v1.GpioMapping>} value
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
*/
proto.oneshelf.v1.OneshelfConfig.prototype.setGpioMappingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 100, value);
};


/**
 * @param {!proto.oneshelf.v1.GpioMapping=} opt_value
 * @param {number=} opt_index
 * @return {!proto.oneshelf.v1.GpioMapping}
 */
proto.oneshelf.v1.OneshelfConfig.prototype.addGpioMappings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 100, opt_value, proto.oneshelf.v1.GpioMapping, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.oneshelf.v1.OneshelfConfig} returns this
 */
proto.oneshelf.v1.OneshelfConfig.prototype.clearGpioMappingsList = function() {
  return this.setGpioMappingsList([]);
};


goog.object.extend(exports, proto.oneshelf.v1);
