# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cfruit/v1/cfruit.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cfruit/v1/cfruit.proto", :syntax => :proto3) do
    add_message "cfruit.v1.CfruitConfig" do
      optional :mqtt_uri, :string, 5
      optional :mqtt_username, :string, 6
      optional :mqtt_password, :string, 7
      optional :mqtt_client_id, :string, 8
      optional :uksr_state, :string, 9
      optional :mineral_path, :string, 10
      optional :iz7k_listen_spec, :string, 2
      optional :gorm_db_engine, :string, 3
      optional :gorm_db_url, :string, 4
      optional :clearly_mac, :string, 20
      optional :item_primary_field, :string, 30
      optional :safety_record_seconds, :uint32, 31
      optional :rssi_attach, :uint32, 41
      optional :rssi_detach, :uint32, 42
      optional :farmer_card_grace, :uint32, 51
    end
    add_message "cfruit.v1.CfruitStateMessage" do
      optional :error, :int32, 1
      optional :antenna_no, :int32, 2
      optional :state, :string, 3
    end
    add_message "cfruit.v1.CfruitStatus" do
      optional :error, :string, 1
      optional :message, :string, 2
    end
    add_message "cfruit.v1.CfruitUserBankData" do
      optional :epc, :string, 1
      optional :app_id, :bytes, 2
    end
  end
end

module Cfruit
  module V1
    CfruitConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cfruit.v1.CfruitConfig").msgclass
    CfruitStateMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cfruit.v1.CfruitStateMessage").msgclass
    CfruitStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cfruit.v1.CfruitStatus").msgclass
    CfruitUserBankData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cfruit.v1.CfruitUserBankData").msgclass
  end
end
