# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ukey/v1/ukey.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ukey/v1/ukey.proto", :syntax => :proto3) do
    add_message "ukey.v1.Ukey" do
      optional :request_id, :uint32, 1
      optional :generation_id, :bytes, 2
      optional :app_id, :bytes, 3
      optional :epc_base, :bytes, 4
      optional :epc_style, :string, 5
      optional :access_base, :bytes, 6
      optional :access_style, :string, 7
      optional :kill_base, :bytes, 8
      optional :kill_style, :string, 9
      optional :confirmation, :bytes, 11
    end
    add_message "ukey.v1.UkeySetResponse" do
      optional :request_id, :uint32, 1
      optional :success, :bool, 2
      optional :message, :string, 3
    end
  end
end

module Ukey
  module V1
    Ukey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ukey.v1.Ukey").msgclass
    UkeySetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ukey.v1.UkeySetResponse").msgclass
  end
end
