# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oled/v1/oled.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("oled/v1/oled.proto", :syntax => :proto3) do
    add_message "oled.v1.Opage" do
      optional :expires_at, :int64, 1
      optional :headline, :string, 2
      optional :line0, :string, 3
      optional :line1, :string, 4
      optional :line2, :string, 5
      optional :line3, :string, 6
      optional :line4, :string, 7
      optional :line5, :string, 8
      optional :line6, :string, 9
      optional :line7, :string, 10
      optional :key, :string, 20
    end
  end
end

module Oled
  module V1
    Opage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("oled.v1.Opage").msgclass
  end
end
