// source: oled/v1/oled.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.oled.v1.Opage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.oled.v1.Opage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.oled.v1.Opage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.oled.v1.Opage.displayName = 'proto.oled.v1.Opage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.oled.v1.Opage.prototype.toObject = function(opt_includeInstance) {
  return proto.oled.v1.Opage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.oled.v1.Opage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oled.v1.Opage.toObject = function(includeInstance, msg) {
  var f, obj = {
    expiresAt: jspb.Message.getFieldWithDefault(msg, 1, 0),
    headline: jspb.Message.getFieldWithDefault(msg, 2, ""),
    line0: jspb.Message.getFieldWithDefault(msg, 3, ""),
    line1: jspb.Message.getFieldWithDefault(msg, 4, ""),
    line2: jspb.Message.getFieldWithDefault(msg, 5, ""),
    line3: jspb.Message.getFieldWithDefault(msg, 6, ""),
    line4: jspb.Message.getFieldWithDefault(msg, 7, ""),
    line5: jspb.Message.getFieldWithDefault(msg, 8, ""),
    line6: jspb.Message.getFieldWithDefault(msg, 9, ""),
    line7: jspb.Message.getFieldWithDefault(msg, 10, ""),
    key: jspb.Message.getFieldWithDefault(msg, 20, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.oled.v1.Opage}
 */
proto.oled.v1.Opage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.oled.v1.Opage;
  return proto.oled.v1.Opage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.oled.v1.Opage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.oled.v1.Opage}
 */
proto.oled.v1.Opage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpiresAt(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setHeadline(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLine0(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLine1(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLine2(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLine3(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLine4(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setLine5(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setLine6(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setLine7(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.oled.v1.Opage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.oled.v1.Opage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.oled.v1.Opage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oled.v1.Opage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExpiresAt();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getHeadline();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLine0();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLine1();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLine2();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLine3();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLine4();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getLine5();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getLine6();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getLine7();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
};


/**
 * optional int64 expires_at = 1;
 * @return {number}
 */
proto.oled.v1.Opage.prototype.getExpiresAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.oled.v1.Opage} returns this
 */
proto.oled.v1.Opage.prototype.setExpiresAt = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string headline = 2;
 * @return {string}
 */
proto.oled.v1.Opage.prototype.getHeadline = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.oled.v1.Opage} returns this
 */
proto.oled.v1.Opage.prototype.setHeadline = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string line0 = 3;
 * @return {string}
 */
proto.oled.v1.Opage.prototype.getLine0 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.oled.v1.Opage} returns this
 */
proto.oled.v1.Opage.prototype.setLine0 = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string line1 = 4;
 * @return {string}
 */
proto.oled.v1.Opage.prototype.getLine1 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.oled.v1.Opage} returns this
 */
proto.oled.v1.Opage.prototype.setLine1 = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string line2 = 5;
 * @return {string}
 */
proto.oled.v1.Opage.prototype.getLine2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.oled.v1.Opage} returns this
 */
proto.oled.v1.Opage.prototype.setLine2 = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string line3 = 6;
 * @return {string}
 */
proto.oled.v1.Opage.prototype.getLine3 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.oled.v1.Opage} returns this
 */
proto.oled.v1.Opage.prototype.setLine3 = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string line4 = 7;
 * @return {string}
 */
proto.oled.v1.Opage.prototype.getLine4 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.oled.v1.Opage} returns this
 */
proto.oled.v1.Opage.prototype.setLine4 = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string line5 = 8;
 * @return {string}
 */
proto.oled.v1.Opage.prototype.getLine5 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.oled.v1.Opage} returns this
 */
proto.oled.v1.Opage.prototype.setLine5 = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string line6 = 9;
 * @return {string}
 */
proto.oled.v1.Opage.prototype.getLine6 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.oled.v1.Opage} returns this
 */
proto.oled.v1.Opage.prototype.setLine6 = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string line7 = 10;
 * @return {string}
 */
proto.oled.v1.Opage.prototype.getLine7 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.oled.v1.Opage} returns this
 */
proto.oled.v1.Opage.prototype.setLine7 = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string key = 20;
 * @return {string}
 */
proto.oled.v1.Opage.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.oled.v1.Opage} returns this
 */
proto.oled.v1.Opage.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


goog.object.extend(exports, proto.oled.v1);
